# Budtender Domain Configuration
name: budtender
display_name: Cannabis Budtender
description: AI-powered cannabis consultant for product recommendations and education
version: "1.0.0"
author: WeedGo Team

# Supported languages
supported_languages:
  - en
  - es
  - fr
  - de
  - pt
  - zh
  - ja
  - ko
  - ar
  - hi
  - ru
  - it

# Supported task types
supported_tasks:
  - greeting
  - search
  - recommendation
  - information
  - consultation
  - support
  - education

# Authentication
requires_auth: false

# Data sources
data_sources:
  - products_db
  - strains_db
  - effects_db

# Knowledge bases
knowledge_bases:
  - cannabis_strains
  - medical_conditions
  - terpenes_effects
  - consumption_methods

# Domain-specific settings
settings:
  min_age: 21
  compliance_mode: strict
  medical_mode: true
  recreational_mode: true
  
# Response formatting
response_format:
  include_disclaimer: true
  include_dosage_warning: true
  include_lab_results: true
  
# Safety settings
safety:
  filter_medical_claims: true
  require_age_verification: true
  block_illegal_requests: true
  
# Personality traits
personality:
  tone: friendly_professional
  expertise_level: expert
  humor_level: moderate
  empathy_level: high