// Table Headers matching Excel exactly
const excelHeaders = [
  'Category', 'Sub-Category', 'Sub-Sub-Category', 'Product Name', 'Brand',
  'Supplier Name', 'Product Short Description', 'Product Long Description',
  'Size', 'Colour', 'Image URL', 'Unit of Measure', 'Stock Status', 'Unit Price',
  'Pack Size', 'Minimum THC Content (%)', 'Maximum THC Content (%)',
  'THC Content Per Unit', 'THC Content Per Volume',
  'Minimum CBD Content (%)', 'Maximum CBD Content (%)',
  'CBD Content Per Unit', 'CBD Content Per Volume',
  'Dried Flower Cannabis Equivalency', 'Plant Type', 'Terpenes',
  'GrowingMethod', 'Number of Items in a Retail Pack', 'GTIN',
  'OCS Item Number', 'OCS Variant Number',
  'Physical Dimension Width', 'Physical Dimension Height', 
  'Physical Dimension Depth', 'Physical Dimension Volume',
  'Physical Dimension Weight', 'Eaches Per Inner Pack',
  'Eaches Per Master Case', 'Inventory Status', 'Storage Criteria',
  'Food Allergens', 'Ingredients', 'Street Name', 'Grow Medium',
  'Grow Method', 'Grow Region', 'Drying Method', 'Trimming Method',
  'Extraction Process', 'Carrier Oil', 'Heating Element Type',
  'Battery Type', 'Rechargeable Battery', 'Removable Battery',
  'Replacement Parts Available', 'Temperature Control',
  'Temperature Display', 'Compatibility', 'THC Min', 'THC Max',
  'CBD Min', 'CBD Max', 'Net Weight', 'Ontario Grown', 'Craft',
  'Fulfilment Method', 'Delivery Tier', 'Strain Type'
];

// Field mapping from database to display
const fieldMapping = {
  'category': 'Category',
  'sub_category': 'Sub-Category', 
  'sub_sub_category': 'Sub-Sub-Category',
  'product_name': 'Product Name',
  'brand': 'Brand',
  'supplier_name': 'Supplier Name',
  'product_short_description': 'Product Short Description',
  'product_long_description': 'Product Long Description',
  'size': 'Size',
  'colour': 'Colour',
  'image_url': 'Image URL',
  'unit_of_measure': 'Unit of Measure',
  'stock_status': 'Stock Status',
  'unit_price': 'Unit Price',
  'pack_size': 'Pack Size',
  'minimum_thc_content_percent': 'Minimum THC Content (%)',
  'maximum_thc_content_percent': 'Maximum THC Content (%)',
  'thc_content_per_unit': 'THC Content Per Unit',
  'thc_content_per_volume': 'THC Content Per Volume',
  'minimum_cbd_content_percent': 'Minimum CBD Content (%)',
  'maximum_cbd_content_percent': 'Maximum CBD Content (%)',
  'cbd_content_per_unit': 'CBD Content Per Unit',
  'cbd_content_per_volume': 'CBD Content Per Volume',
  'dried_flower_cannabis_equivalency': 'Dried Flower Cannabis Equivalency',
  'plant_type': 'Plant Type',
  'terpenes': 'Terpenes',
  'growing_method': 'GrowingMethod',
  'number_of_items_in_retail_pack': 'Number of Items in a Retail Pack',
  'gtin': 'GTIN',
  'ocs_item_number': 'OCS Item Number',
  'ocs_variant_number': 'OCS Variant Number',
  'physical_dimension_width': 'Physical Dimension Width',
  'physical_dimension_height': 'Physical Dimension Height',
  'physical_dimension_depth': 'Physical Dimension Depth',
  'physical_dimension_volume': 'Physical Dimension Volume',
  'physical_dimension_weight': 'Physical Dimension Weight',
  'eaches_per_inner_pack': 'Eaches Per Inner Pack',
  'eaches_per_master_case': 'Eaches Per Master Case',
  'inventory_status': 'Inventory Status',
  'storage_criteria': 'Storage Criteria',
  'food_allergens': 'Food Allergens',
  'ingredients': 'Ingredients',
  'street_name': 'Street Name',
  'grow_medium': 'Grow Medium',
  'grow_method': 'Grow Method',
  'grow_region': 'Grow Region',
  'drying_method': 'Drying Method',
  'trimming_method': 'Trimming Method',
  'extraction_process': 'Extraction Process',
  'carrier_oil': 'Carrier Oil',
  'heating_element_type': 'Heating Element Type',
  'battery_type': 'Battery Type',
  'rechargeable_battery': 'Rechargeable Battery',
  'removable_battery': 'Removable Battery',
  'replacement_parts_available': 'Replacement Parts Available',
  'temperature_control': 'Temperature Control',
  'temperature_display': 'Temperature Display',
  'compatibility': 'Compatibility',
  'thc_min': 'THC Min',
  'thc_max': 'THC Max',
  'cbd_min': 'CBD Min',
  'cbd_max': 'CBD Max',
  'net_weight': 'Net Weight',
  'ontario_grown': 'Ontario Grown',
  'craft': 'Craft',
  'fulfilment_method': 'Fulfilment Method',
  'delivery_tier': 'Delivery Tier',
  'strain_type': 'Strain Type'
};

export { excelHeaders, fieldMapping };