version: '3.8'

# Test Environment Docker Compose
# Ports: Backend 6024
# Uses same local DB and Redis as dev environment (just different backend port)

services:
  ai-engine-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: weedgo-ai-engine-test
    ports:
      - "6024:6024"
    env_file:
      - .env.test
    environment:
      # Connect to host machine's local database and redis
      DATABASE_URL: postgresql://${DB_USER:-weedgo}:${DB_PASSWORD:-weedgo123}@host.docker.internal:${DB_PORT:-5432}/${DB_NAME:-ai_engine_test}
      REDIS_URL: redis://host.docker.internal:6379/0
      ENVIRONMENT: test
      PORT: 6024
      V5_PORT: 6024
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
