# AI Engine Configuration
# Central configuration for AI behaviors and settings

# Database configuration
database:
  host: localhost
  port: 5434
  user: weedgo
  password: weedgo123
  name: ai_engine

# Default AI role
default_role: budtender

# Model configuration
models:
  default: deepseek-coder-6.7b-instruct.Q4_K_M
  multilingual:
    - qwen2.5-7b-instruct-q4_k_m
    - llama-3.3-70b-instruct-q4_k_m
  reasoning:
    - qwq-32b-preview-q4_k_m
  coding:
    - deepseek-coder-v2-lite-instruct-q4_k_m

# Behavior configuration
behaviors:
  intent_detection:
    enabled: true
    confidence_threshold: 0.7
  language_detection:
    enabled: true
    auto_translate: true
  sentiment_analysis:
    enabled: true
    track_frustration: true
  conversation_management:
    context_window: 10
    remember_preferences: true

# Performance settings
performance:
  max_concurrent_requests: 10
  response_timeout: 30
  cache_ttl: 3600
  enable_streaming: false