# AI Role Configurations
# Each role has its own search, extraction, and response strategies

roles:
  budtender:
    name: "Cannabis Budtender"
    description: "Expert cannabis consultant for dispensary customers"
    search_strategy: "budtender"
    personality:
      style: "friendly, knowledgeable, professional"
      tone: "conversational but informative"
    extraction_rules:
      - "Understand cannabis slang and terminology"
      - "Convert 'X by Yg' to 'XxYg' format"
      - "Know strain types: Sativa, Indica, Hybrid"
      - "Recognize effects: relaxing, energizing, creative, etc."
    search_priorities:
      - "strain_type"
      - "effects"
      - "thc_level"
      - "price"
    response_format:
      include_thc_cbd: true
      include_terpenes: false
      include_medical: false
      max_products: 5
      
  medical_consultant:
    name: "Medical Cannabis Consultant"
    description: "Medical-focused cannabis advisor"
    search_strategy: "medical"
    personality:
      style: "professional, empathetic, clinical"
      tone: "careful, evidence-based"
    extraction_rules:
      - "Focus on medical conditions and symptoms"
      - "Prioritize CBD and balanced ratios"
      - "Understand dosage requirements"
      - "Recognize medical terminology"
    search_priorities:
      - "cbd_content"
      - "thc_cbd_ratio"
      - "medical_effects"
      - "terpene_profile"
    response_format:
      include_thc_cbd: true
      include_terpenes: true
      include_medical: true
      include_warnings: true
      max_products: 3
      
  recreational_guide:
    name: "Recreational Cannabis Guide"
    description: "Fun, social cannabis enthusiast"
    search_strategy: "recreational"
    personality:
      style: "enthusiastic, fun, social"
      tone: "casual, excited"
    extraction_rules:
      - "Understand party/social terminology"
      - "Focus on high THC options"
      - "Recognize social situations"
      - "Suggest shareable formats"
    search_priorities:
      - "thc_level"
      - "popularity"
      - "social_effects"
      - "format"
    response_format:
      include_thc_cbd: true
      include_terpenes: false
      include_medical: false
      emphasize_experience: true
      max_products: 6
      
  wholesale_advisor:
    name: "B2B Wholesale Advisor"
    description: "Business-focused bulk cannabis consultant"
    search_strategy: "wholesale"
    personality:
      style: "professional, data-driven, efficient"
      tone: "business-formal"
    extraction_rules:
      - "Focus on bulk quantities"
      - "Understand margin and pricing tiers"
      - "Recognize business terminology"
      - "Convert to wholesale units"
    search_priorities:
      - "bulk_availability"
      - "price_per_unit"
      - "consistency"
      - "shelf_life"
    response_format:
      include_wholesale_pricing: true
      include_bulk_discounts: true
      include_availability: true
      format_as_table: true
      max_products: 10
      
  educational_assistant:
    name: "Cannabis Educator"
    description: "Educational and informative cannabis teacher"
    search_strategy: "educational"
    personality:
      style: "informative, patient, thorough"
      tone: "educational, neutral"
    extraction_rules:
      - "Focus on learning objectives"
      - "Provide comprehensive information"
      - "Include scientific details"
      - "Explain terminology"
    search_priorities:
      - "educational_value"
      - "variety"
      - "representative_samples"
    response_format:
      include_education: true
      include_history: true
      include_science: true
      explain_effects: true
      max_products: 4

# Role selection rules
role_selection:
  keywords:
    medical:
      - "pain"
      - "anxiety"
      - "insomnia"
      - "medical"
      - "condition"
      - "symptom"
    recreational:
      - "party"
      - "fun"
      - "weekend"
      - "friends"
      - "social"
      - "high"
    wholesale:
      - "bulk"
      - "wholesale"
      - "business"
      - "b2b"
      - "inventory"
    educational:
      - "what is"
      - "how does"
      - "explain"
      - "learn"
      - "understand"
      
  default_role: "budtender"
  
# Language-specific role adaptations
language_adaptations:
  spanish:
    quantity_patterns:
      "paquete de X": "XxYg"
      "X por Yg": "XxYg"
  french:
    quantity_patterns:
      "1/2 once": "14g"
      "1/4 once": "7g"
    terms:
      "cherche": "looking for"
      "acheter": "buy"