# Domain Configuration
# Specifies which domains are enabled and their settings

# List of enabled domains
enabled_domains:
  - budtender
  - healthcare
  # - legal        # Add when implemented
  # - education    # Add when implemented
  # - finance      # Add when implemented

# Default domain when none specified
default_domain: budtender

# Auto-discover new domains in the domains/ folder
auto_discover: true

# Data adapter configurations
data_adapters:
  products_db:
    type: postgresql
    host: localhost
    port: 5434
    database: ai_engine
    user: ai_user
    password: ai_password
    min_connections: 2
    max_connections: 10
    
  medical_db:
    type: postgresql
    host: localhost
    port: 5432
    database: medical
    user: medical_user
    password: ${MEDICAL_DB_PASSWORD}
    min_connections: 1
    max_connections: 5
    
  # Can add other adapter types
  knowledge_vector_db:
    type: chromadb
    host: localhost
    port: 8000
    collection: knowledge
    
  external_api:
    type: api
    base_url: https://api.example.com
    api_key: ${API_KEY}

# Global settings
settings:
  # Maximum context history per session
  max_context_history: 20
  
  # Session timeout in seconds
  session_timeout: 3600
  
  # Enable domain auto-switching based on query
  auto_switch_domains: false
  
  # Log all interactions
  log_interactions: true
  
  # Compliance mode
  compliance_mode: strict
  
  # Multi-language settings
  default_language: en
  auto_detect_language: true
  
  # Model settings
  model_selection: automatic
  prefer_speed: false
  
  # Safety settings
  content_filtering: true
  age_verification: true
  
  # Feature flags
  features:
    knowledge_search: true
    session_context: true
    multi_domain: true
    tool_use: true
    escalation: true