# Healthcare Domain Configuration
name: healthcare
display_name: Healthcare Assistant
description: AI-powered healthcare information and wellness guidance
version: "1.0.0"
author: Demo Team

# Supported languages
supported_languages:
  - en
  - es
  - fr
  - de
  - zh
  - ja
  - ko
  - ar
  - hi
  - pt

# Supported task types
supported_tasks:
  - greeting
  - search
  - recommendation
  - information
  - consultation
  - support
  - education

# Authentication
requires_auth: true

# Data sources
data_sources:
  - medical_db
  - symptoms_db
  - medications_db

# Knowledge bases
knowledge_bases:
  - medical_conditions
  - symptoms_checker
  - medications
  - wellness_tips

# Domain-specific settings
settings:
  compliance_mode: strict
  disclaimer_required: true
  emergency_detection: true
  
# Response formatting
response_format:
  include_disclaimer: true
  include_emergency_info: true
  include_sources: true
  
# Safety settings
safety:
  no_diagnosis: true
  no_prescription: true
  require_professional_referral: true
  emergency_escalation: true
  
# Personality traits
personality:
  tone: caring_professional
  expertise_level: informative
  empathy_level: very_high
  urgency_detection: true