-- =====================================================
-- Add Super Admin User
-- Email: admin@weedgo.ca
-- Password: Password1$
-- Date: 2025-01-11
-- =====================================================

BEGIN;

-- First, create a default tenant for the super admin
INSERT INTO tenants (
    id,
    name,
    code,
    company_name,
    contact_email,
    status,
    subscription_tier,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(),
    'WeedGo System',
    'WEEDGO',
    'WeedGo Technologies Inc.',
    'admin@weedgo.ca',
    'active',
    'enterprise',
    NOW(),
    NOW()
) ON CONFLICT (code) DO NOTHING
RETURNING id;

-- Store the tenant ID for use in subsequent inserts
DO $$
DECLARE
    v_tenant_id UUID;
    v_user_id UUID;
    v_hashed_password TEXT;
BEGIN
    -- Get or create the system tenant
    SELECT id INTO v_tenant_id 
    FROM tenants 
    WHERE code = 'WEEDGO'
    LIMIT 1;
    
    IF v_tenant_id IS NULL THEN
        INSERT INTO tenants (
            id,
            name,
            code,
            company_name,
            contact_email,
            status,
            subscription_tier,
            created_at,
            updated_at
        ) VALUES (
            gen_random_uuid(),
            'WeedGo System',
            'WEEDGO',
            'WeedGo Technologies Inc.',
            'admin@weedgo.ca',
            'active',
            'enterprise',
            NOW(),
            NOW()
        ) RETURNING id INTO v_tenant_id;
    END IF;

    -- Generate a UUID for the user
    v_user_id := gen_random_uuid();
    
    -- Hash the password using bcrypt
    -- Note: This is the bcrypt hash for 'Password1$'
    -- In production, this should be generated by the application
    v_hashed_password := '$2b$12$qGed8TgtYgNsF2PH6V/AqeDv8V/jXMTmTyRbRhm/1UdxqrBh1737u';

    -- Create the super admin user
    INSERT INTO users (
        id,
        email,
        password_hash,
        first_name,
        last_name,
        active,
        email_verified,
        tenant_id,
        created_at,
        updated_at
    ) VALUES (
        v_user_id,
        'admin@weedgo.ca',
        v_hashed_password,
        'System',
        'Administrator',
        true,
        true,
        v_tenant_id,
        NOW(),
        NOW()
    ) ON CONFLICT (email) DO UPDATE SET
        password_hash = v_hashed_password,
        active = true,
        email_verified = true,
        tenant_id = v_tenant_id,
        updated_at = NOW();

    -- Get the user ID if it was updated
    SELECT id INTO v_user_id FROM users WHERE email = 'admin@weedgo.ca';

    -- Link the super admin to the system tenant in tenant_users table
    INSERT INTO tenant_users (
        id,
        tenant_id,
        user_id,
        role,
        is_active,
        created_at,
        updated_at
    ) VALUES (
        gen_random_uuid(),
        v_tenant_id,
        v_user_id,
        'super_admin',
        true,
        NOW(),
        NOW()
    ) ON CONFLICT (tenant_id, user_id) DO UPDATE SET
        role = 'super_admin',
        is_active = true,
        updated_at = NOW();

    RAISE NOTICE 'Super admin user created successfully';
    RAISE NOTICE 'Email: admin@weedgo.ca';
    RAISE NOTICE 'Password: Password1$';
    RAISE NOTICE 'Tenant ID: %', v_tenant_id;
    RAISE NOTICE 'User ID: %', v_user_id;
END $$;

COMMIT;

-- Verify the super admin was created
SELECT 
    u.id,
    u.email,
    u.first_name || ' ' || u.last_name as full_name,
    u.active,
    u.email_verified,
    t.name as tenant_name,
    t.subscription_tier,
    tu.role as tenant_role
FROM users u
LEFT JOIN tenant_users tu ON tu.user_id = u.id
LEFT JOIN tenants t ON t.id = tu.tenant_id
WHERE u.email = 'admin@weedgo.ca';